### ISSUE TITLE
Make the import scripts more fault tolerant

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#18]
Arising from the discusson in #16, it occurs to me that the possibility of failing an entire transaction of _n_ days because an individual row contains questionable data is somewhat brittle.

I presume that pushing the transaction down to the event level would kill performance completely, so do we need to look at some kind of pre-processing step in which we can ditch suspect data? Or maybe some logic to re-try a transaction without the failing row? (although that would also be really slow if there are lots of them)

@rfk, thoughts?

**Comment by rfk** [comment]
It would be worth trying.  The `COPY` command does have some facility for ignoring errors, so we might be able to say "just ignore the first 100 errors, fail out if there's more than that".

Or at the very least, we could have it email us about any errors rather than sending them to `/var/spool/mail/ec2-user` on that redshift helper instance :-)

**Comment by philbooth** [comment]
I feel like this issue is addressed by a combination of #22, #27, mozilla/fxa-content-server#4383, mozilla/fxa-content-server#4415 and mozilla/fxa-auth-server#1543.

@rfk, what do you reckon?

**Comment by rfk** [comment]
Yes, thanks @philbooth, let's re-open specific issues if we continue to find problems.
