### ISSUE TITLE
Flows that contain `flow.complete`, but have `completed=false`

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-activity-metrics#51]
Here's something odd I noticed:

  https://sql.telemetry.mozilla.org/queries/3026/source?p_interval=7

That query selects flows that contain a `flow.complete` event, but for which the `flow_metadata.completed` column has not been set to true.  It looks like they're all in the most recently-imported day.  @philbooth any clue why this might be happening?  Will they get correctly marked as `completed=true` when the next daily import runs?

**Comment by rfk** [comment]
> It looks like they're all in the most recently-imported day

Actually this may have been a problem with the pagination in re:dash, I'm not sure it's actually true.

**Comment by philbooth** [comment]
I broke this on 17th December when I [changed the `UPDATE` queries to work against `flow_events` instead of `temporary_raw_flow_data`](https://github.com/mozilla/fxa-activity-metrics/commit/73631a146e9dca1c479d21d647abfc7920e80489#diff-765de41a01f9e2f8bb16ea58c3b7d978R200) but [failed to move the `INSERT INTO flow_events` so that it occurs before those queries](https://github.com/mozilla/fxa-activity-metrics/commit/73631a146e9dca1c479d21d647abfc7920e80489#diff-765de41a01f9e2f8bb16ea58c3b7d978R323).

Then, over Christmas, I did a complete re-import of the flow data and we ended up with this sorry state of affairs:

```
fxa=# select count(*) from flow_metadata where duration > 0;
 count
-------
  6406
(1 row)

fxa=# select count(*) from flow_metadata where completed = TRUE;
 count
-------
    36
(1 row)

fxa=# select count(*) from flow_metadata where new_account = TRUE;
 count
-------
    46
(1 row)
```

I'm surprised that none of those are zero to be honest, not sure where they got their values from. Anyway, fix incoming and apologies for not catching this at the time.
