### ISSUE TITLE
Add email provider to flow_meta data

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-activity-metrics#66]
In order to measure to detect possible mail deliverability problems and their impact on login and registration, we would like to be able to segment flow events by top email provider.

This will potentially be required to measure the success of a KR in Q2.

**Comment by shane-tomlinson** [comment]
@vbudhram says this is active

**Comment by rfk** [comment]
We can do this now, see e.g:

  https://sql.telemetry.mozilla.org/queries/4246/source#8461

@vbudhram is there anything else you want to do here?  We could e.g. add an "email provider" column directly to the flow_metadata table, rather than looking it up through a join like we currently do.  But I'm not sure how much that'd win us in practice.

**Comment by vbudhram** [comment]
> But I'm not sure how much that'd win us in practice.

Yea I'm not 100% sure either. However, I think it should be fine for now. Maybe if the queries start taking really long we can reconsider? Other than that I think this is good to close.

**Comment by rfk** [comment]
OK, let's close this one and reconsider if the joins become too painful.
