### ISSUE TITLE
Add Redshift Nodes?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-activity-metrics#75]
During the work week in MTV, @jbuck mentioned that we only had 1 Redshift node for our metrics and that it would be pretty trivial to add another. He also mentioned that the cost would not be very high.

This issue is to review:
- if adding a node would help with query performance
- if adding a node is actually easy
- if the the cost is as low as what was mentioned during work week
- if the answers to the above are yes, do we want to move forward with it?

I would also suspect that this would only be in the interim while we do a review of newer faster tools.

**Comment by jbuck** [comment]
> - if adding a node would help with query performance

I think we'll need to test a multi-node cluster to see if it helps with performance. @philbooth is this something that you might have time for? We could spin up a 3-node cluster that's otherwise exactly the same as the current redshift db. We could also looking at switching to a dc1.large instance. They're about 1/3rd the price of the single ds2.large we're currently using.

> - if adding a node is actually easy

Very easy, the cluster goes into a read-only state while it resizes itself. Only problem is if you have a dataset that doesn't fit into your new cluster configuration...

> - if the the cost is as low as what was mentioned during work week

<table><colgroup><col style="width: 16%"><col style="width: 14%"><col style="width: 14%"><col style="width: 14%"><col style="width: 14%"><col style="width: 14%"><col style="width: 14%"></colgroup><thead><tr><th></th><th class="rate">vCPU</th><th class="rate">ECU</th><th class="rate">Memory (GiB)</th><th class="rate">Storage</th><th class="rate">I/O</th><th class="rate">Price</th></tr></thead><tbody class="body"><tr class="heading"><th class="type" colspan="7">Dense Compute</th></tr><tr class="tiers"><td class="size">dc1.large</td><td class="vCPU">2</td><td class="ECU">7</td><td class="memory">15</td><td class="storage">0.16TB SSD</td><td class="io">0.20GB/s</td><td class="rate yrTerm1Hourly">$0.250 per Hour</td></tr><tr class="tiers"><td class="size">dc1.8xlarge</td><td class="vCPU">32</td><td class="ECU">104</td><td class="memory">244</td><td class="storage">2.56TB SSD</td><td class="io">3.70GB/s</td><td class="rate yrTerm1Hourly">$4.800 per Hour</td></tr></tbody><tbody class="body"><tr class="heading"><th class="type" colspan="7">Dense Storage</th></tr><tr class="tiers"><td class="size">ds2.xlarge</td><td class="vCPU">4</td><td class="ECU">14</td><td class="memory">31</td><td class="storage">2TB HDD</td><td class="io">0.40GB/s</td><td class="rate yrTerm1Hourly">$0.850 per Hour</td></tr><tr class="tiers"><td class="size">ds2.8xlarge</td><td class="vCPU">36</td><td class="ECU">116</td><td class="memory">244</td><td class="storage">16TB HDD</td><td class="io">3.30GB/s</td><td class="rate yrTerm1Hourly">$6.800 per Hour</td></tr></tbody></table>

In terms of costing, we're currently using a single node ds2.xlarge node. I don't think we used reserved instances for this, so it costs $637.50/month.

We could look at moving to a multi-node ds2.large cluster, but I think we should seriously consider moving to a 3 or 4 multi-node dc1.large cluster. It'd give us a performance increase at a similar cost.

**Comment by philbooth** [comment]
> @philbooth is this something that you might have time for?

Absolutely. Happy to do any re-importing as well as timing comparisons for meaty queries between the two clusters.

One thing to note if we're taking timings though, is that the current cluster gets hammered by all the scheduled queries that are usually running (including multiple copies of the same query, see [bug 1323840](https://bugzilla.mozilla.org/show_bug.cgi?id=1323840)). It can be tricky to find a quiet time to run the queries there, in order to make a fair comparison. Maybe we could agree for everyone to disable their scheduled queries for a weekend or something.

**Comment by jbuck** [comment]
@philbooth excellent. I'm wondering if finishing #73 first is a good idea, because then we could try 3-4 dc1.larges vs the current ds2.large . Right now the ds2.large uses 50% of 2TB, but the test zstd cluster you have running is only using 3% of 160GB.

**Comment by philbooth** [comment]
> Right now the ds2.large uses 50% of 2TB, but the test zstd cluster you have running is only using 3% of 160GB.

Actually, that test cluster hasn't been updated to zstd yet, I was having problems with the update script earlier. The difference in disk usage you mentioned is because it only contains a subset of the data (just `flow_events`, `flow_experiments` and `flow_metadata`). The main cluster also has our activity event data, which goes back to the start of 2016.

**Comment by rfk** [comment]
FWIW I am +1 to throwing some money at our metrics performance issues in the hope that they'll go away, so this sounds like a fine plan to me!

**Comment by vladikoff** [comment]
Done!
